apiVersion: batch/v1
kind: Job
metadata:
  name: db-check
  annotations: 
    argocd.argoproj.io/sync-wave: "2
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation, HookSucceeded
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: check
          image: busybox
          command:
            - "sh"
            - "-c"
            - "echo 'Running db check to $DB_HOST ....'; sleep 10; echo 'Connected!'"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_host
